# Generated by Django 3.1.1 on 2020-10-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='bottols',
            field=models.IntegerField(default='0'),
        ),
    ]
