# Generated by Django 3.1.1 on 2020-10-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_stock_bottols'),
    ]

    operations = [
        migrations.AddField(
            model_name='saletrans',
            name='bottols',
            field=models.IntegerField(default='0'),
        ),
    ]
